description: "Сводные данные"
get:
    description: "Возвращает все сводные данные в виде дерева"
    is: !include /../../../vendor/yii2lab/yii2-rest/src/domain/docs/is/simple/one.raml
    responses:
        200:
            body:
                application/json:
                    example: !include example/tree.json
